### ISSUE TITLE
Comfyui Lora's reasoning failed

### ISSUE THREAD

**Issue by Wangzhipeng777** [aigc-apps/EasyAnimate#116]
I moved the output dir/checkpoint-1500 to the models/lora folder and attempted inference in comfyui, but encountered a failure

Training parameters
accelerate launch --mixed_precision="bf16" train.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATASET_NAME \
  --train_data_meta=$DATASET_META_NAME \
  --config_path "EasyAnimate/config/easyanimate_video_slicevae_motion_module_v3.yaml" \
  --image_sample_size=960 \
  --video_sample_size=960 \
  --token_sample_size=512 \
  --video_sample_stride=1 \
  --video_sample_n_frames=144 \
  --train_batch_size=1 \
  --video_repeat=1 \
  --gradient_accumulation_steps=1 \
  --dataloader_num_workers=8 \
  --num_train_epochs=100 \
  --checkpointing_steps=500 \
  --learning_rate=2e-05 \
  --lr_scheduler="constant_with_warmup" \
  --lr_warmup_steps=100 \
  --seed=42 \
  --output_dir="output_dir" \
  --enable_xformers_memory_efficient_attention \
  --gradient_checkpointing \
  --mixed_precision="bf16" \
  --adam_weight_decay=3e-2 \
  --adam_epsilon=1e-10 \
  --vae_mini_batch=1 \
  --max_grad_norm=1 \
  --random_hw_adapt \
  --training_with_video_token_length \
  --motion_sub_loss \
  --random_frame_crop \
  --enable_bucket \
  --train_mode="inpaint" \
  --trainable_modules "transformer_blocks" "proj_out" "pos_embed" "long_connect_fc"

Error message
!!! Exception during processing!!! not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/mnt_alipayshnas/workspace/shangge/ais_default_code_config_repo_449641/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt_alipayshnas/workspace/shangge/ais_default_code_config_repo_449641/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt_alipayshnas/workspace/shangge/ais_default_code_config_repo_449641/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt_alipayshnas/workspace/shangge/ais_default_code_config_repo_449641/ComfyUI/custom_nodes/EasyAnimate/comfyui/comfyui_nodes.py", line 354, in process
    pipeline = merge_lora(pipeline, _lora_path, _lora_weight)
  File "/mnt_alipayshnas/workspace/shangge/ais_default_code_config_repo_449641/ComfyUI/custom_nodes/EasyAnimate/easyanimate/utils/lora_utils.py", line 378, in merge_lora
    layer, elem = key.split('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by yunkchen** [comment]
你训练的不是LoRA；
训练的output放到custom_nodes/EasyAnimate/models/Diffusion_Transformer/
