### ISSUE TITLE
能否出一个comfyui的安装教程啊！包括环境部署

### ISSUE THREAD

**Issue by itjsp** [aigc-apps/EasyAnimate#118]
环境部署实在太难了，

**Comment by itjsp** [comment]
安装总是不成功
E:\ComfyUI-aki-v1.3\custom_nodes\EasyAnimate>python install.py
 Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
 Requirement already satisfied: Pillow in c:\users\91906\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 1)) (10.2.0)
 Collecting einops (from -r requirements.txt (line 2))
   Using cached https://mirrors.aliyun.com/pypi/packages/44/5a/f0b9ad6c0a9017e62d4735daaeb11ba3b6c009d69a26141b258cd37b5588/einops-0.8.0-py3-none-any.whl (43 kB)
 Collecting safetensors (from -r requirements.txt (line 3))
   Using cached https://mirrors.aliyun.com/pypi/packages/ba/f0/919c72a9eef843781e652d0650f2819039943e69b69d5af2d0451a23edc3/safetensors-0.4.5-cp310-none-win_amd64.whl (285 kB)
 Collecting timm (from -r requirements.txt (line 4))
   Using cached https://mirrors.aliyun.com/pypi/packages/e7/0e/ef97f6d8c399bf5842af0dd5a4f5ac55b2f169d62e29ecbf7663e1cb1438/timm-1.0.9-py3-none-any.whl (2.3 MB)
 Collecting tomesd (from -r requirements.txt (line 5))
   Downloading https://mirrors.aliyun.com/pypi/packages/0c/02/367c67c8f510313f143a7818e92254a5f861c7d94c98ad6a08d25db52fee/tomesd-0.1.3-py3-none-any.whl (11 kB)
 Requirement already satisfied: torch>=2.1.2 in c:\users\91906\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 6)) (2.3.1)
 Collecting torchdiffeq (from -r requirements.txt (line 7))
   Using cached https://mirrors.aliyun.com/pypi/packages/84/64/85249acbac630f34cd113dca4b1a72f55d3ad4c26bc9305a27aef6049756/torchdiffeq-0.2.4-py3-none-any.whl (32 kB)
 Collecting torchsde (from -r requirements.txt (line 8))
   Using cached https://mirrors.aliyun.com/pypi/packages/dd/1f/b67ebd7e19ffe259f05d3cf4547326725c3113d640c277030be3e9998d6f/torchsde-0.2.6-py3-none-any.whl (61 kB)
 Requirement already satisfied: xformers in c:\users\91906\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 9)) (0.0.27)
 Collecting decord (from -r requirements.txt (line 10))
   Downloading https://mirrors.aliyun.com/pypi/packages/6c/be/e15b5b866da452e62635a7b27513f31cb581fa2ea9cc9b768b535d62a955/decord-0.6.0-py3-none-win_amd64.whl (24.7 MB)
      --------------------------------------- 24.7/24.7 MB 11.9 MB/s eta 0:00:00
 Collecting datasets (from -r requirements.txt (line 11))
   Downloading https://mirrors.aliyun.com/pypi/packages/a5/52/45dab187f03d48c765b94db0464f5c10431756e47ae4cc6a8029a7d57a36/datasets-3.0.0-py3-none-any.whl (474 kB)
 Requirement already satisfied: numpy in c:\users\91906\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 12)) (1.26.4)
 Collecting scikit-image (from -r requirements.txt (line 13))
   Downloading https://mirrors.aliyun.com/pypi/packages/99/89/3fcd68d034db5d29c974e964d03deec9d0fbf9410ff0a0b95efff70947f6/scikit_image-0.24.0-cp310-cp310-win_amd64.whl (12.9 MB)
      --------------------------------------- 12.9/12.9 MB 11.9 MB/s eta 0:00:00
 Requirement already satisfied: opencv-python in c:\users\91906\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 14)) (4.9.0.80)
 Collecting omegaconf (from -r requirements.txt (line 15))
   Downloading https://mirrors.aliyun.com/pypi/packages/e3/94/1843518e420fa3ed6919835845df698c7e27e183cb997394e4a670973a65/omegaconf-2.3.0-py3-none-any.whl (79 kB)
 Collecting SentencePiece (from -r requirements.txt (line 16))
   Downloading https://mirrors.aliyun.com/pypi/packages/85/f4/4ef1a6e0e9dbd8a60780a91df8b7452ada14cfaa0e17b3b8dfa42cecae18/sentencepiece-0.2.0-cp310-cp310-win_amd64.whl (991 kB)
      ------------------------------------- 991.5/991.5 kB 11.8 MB/s eta 0:00:00
 Collecting albumentations (from -r requirements.txt (line 17))
   Downloading https://mirrors.aliyun.com/pypi/packages/2f/38/2011d955445737eb91d6e69c4309637b360f696040943b31b7a44ee6cc88/albumentations-1.4.15-py3-none-any.whl (200 kB)
 Collecting tensorboard (from -r requirements.txt (line 20))
   Downloading https://mirrors.aliyun.com/pypi/packages/d4/41/dccba8c5f955bc35b6110ff78574e4e5c8226ad62f08e732096c3861309b/tensorboard-2.17.1-py3-none-any.whl (5.5 MB)
      ---------------------------------------- 5.5/5.5 MB 12.4 MB/s eta 0:00:00
 Collecting beautifulsoup4 (from -r requirements.txt (line 21))
   Downloading https://mirrors.aliyun.com/pypi/packages/b1/fe/e8c672695b37eecc5cbf43e1d0638d88d66ba3a44c4d321c796f4e59167f/beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
 Collecting ftfy (from -r requirements.txt (line 22))
   Downloading https://mirrors.aliyun.com/pypi/packages/ed/46/14d230ad057048aea7ccd2f96a80905830866d281ea90a6662a825490659/ftfy-6.2.3-py3-none-any.whl (43 kB)
 Collecting func_timeout (from -r requirements.txt (line 23))
   Downloading https://mirrors.aliyun.com/pypi/packages/b3/0d/bf0567477f7281d9a3926c582bfef21bff7498fc0ffd3e9de21811896a0b/func_timeout-4.3.5.tar.gz (44 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'done'
   Preparing metadata (pyproject.toml): started
   Preparing metadata (pyproject.toml): finished with status 'done'
 Collecting deepspeed (from -r requirements.txt (line 24))
   Downloading https://mirrors.aliyun.com/pypi/packages/09/48/915599bbe9e47b59cfc148937fb537d53bad2ea71121a74fec13214bc33a/deepspeed-0.15.1.tar.gz (1.4 MB)
      ---------------------------------------- 1.4/1.4 MB 8.9 MB/s eta 0:00:00
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [20 lines of output]
[!]   [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
[!]   [93m [WARNING] [0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
[!]   DS_BUILD_OPS=1
[!]   Traceback (most recent call last):
[!]     File "C:\Users\91906\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "C:\Users\91906\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]     File "C:\Users\91906\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]     File "C:\Users\91906\AppData\Local\Temp\pip-build-env-tw7dak1m\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=[])
[!]     File "C:\Users\91906\AppData\Local\Temp\pip-build-env-tw7dak1m\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
[!]       self.run_setup()
[!]     File "C:\Users\91906\AppData\Local\Temp\pip-build-env-tw7dak1m\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
[!]       super().run_setup(setup_script=setup_script)
[!]     File "C:\Users\91906\AppData\Local\Temp\pip-build-env-tw7dak1m\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 155, in <module>
[!]   AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\custom_nodes\EasyAnimate\install.py", line 38, in <module>
    assert process_wrap([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"], cwd_path=os.path.dirname(os.path.realpath(__file__))) == 0, "ERROR: Failed to install requirements.txt. Please install them manually, and restart ComfyUI."
AssertionError: ERROR: Failed to install requirements.txt. Please install them manually, and restart ComfyUI.
