### ISSUE TITLE
local variable 'videos' referenced before assignment

### ISSUE THREAD

**Issue by SUP3RMASS1VE** [aigc-apps/EasyAnimate#136]
!!! Exception during processing !!! local variable 'videos' referenced before assignment
Traceback (most recent call last):
  File "F:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\pinokio\api\comfy.git\app\custom_nodes\EasyAnimate\comfyui\comfyui_nodes.py", line 648, in process
    return (videos,)
UnboundLocalError: local variable 'videos' referenced before assignment

**Comment by bubbliiiing** [comment]
Fixed in https://github.com/aigc-apps/EasyAnimate/pull/140
