### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by liubin79813** [aigc-apps/EasyAnimate#147]
hey,bro,I have a running issue in comfyui, which is as follows:

pytorch version: 2.4.1+cu124
WARNING: Failed to find MSVC.
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention

got prompt
### unexpected keys: 0;
[] []
loaded 3D transformer's pretrained weights from E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\models\EasyAnimate\EasyAnimateV5-12b-zh-InP\transformer ...
!!! Exception during processing !!! Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\EasyAnimate\comfyui\comfyui_nodes.py", line 161, in loadmodel
    transformer = Choosen_Transformer3DModel.from_pretrained_2d(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\EasyAnimate\easyanimate\models\transformer3d.py", line 1383, in from_pretrained_2d
    config = json.load(f)
             ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Prompt executed in 1.32 seconds

-----------------------------------------------------------------------------------------------------
Please help me solve it

**Comment by bubbliiiing** [comment]
Can you provide the details of your 'E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\models\EasyAnimate\EasyAnimateV5-12b-zh-InP\transformer\config.json' file?

**Comment by liubin79813** [comment]
[config.json](https://github.com/user-attachments/files/17730847/config.json)

here it is.

**Comment by liubin79813** [comment]
I checked and it seems that I downloaded an incorrect file. I downloaded it again and it seems to work, but after running for a while, it still reported the error from earlier.

got prompt
### missing keys: 0;
### unexpected keys: 0;
[] []
loaded 3D transformer's pretrained weights from E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\models\EasyAnimate\EasyAnimateV5-12b-zh-InP\transformer ...
### missing keys: 0;
### unexpected keys: 0;
[]
### All Parameters: 11797.69248 M
### attn1 Parameters: 1812.54144 M
!!! Exception during processing !!! Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\ComfyUI\custom_nodes\EasyAnimate\comfyui\comfyui_nodes.py", line 170, in loadmodel
    tokenizer = BertTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Mie_V3.0\ComfyUI_Mie_3.0\ComfyUI_Mie_V3.0\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2152, in from_pretrained
    tokenizer_config = json.load(reader)
                       ^^^^^^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Prompt executed in 120.10 seconds

**Comment by bubbliiiing** [comment]
This is not right, it should be like this. ![image](https://github.com/user-attachments/assets/8c90f489-cba6-4017-84a0-827026c5cc90)

**Comment by bubbliiiing** [comment]
> nodes.py", line 170, in loadmodel
> tokenizer = BertTokenizer.from_pretrained(

How did you download the weights? It seems that there is a significant issue with the weights.
