### ISSUE TITLE
Image to video issue 

### ISSUE THREAD

**Issue by noflytm** [aigc-apps/EasyAnimate#153]
Hello team,
Could you please give me a tip about image-to-video and what might be wrong? I can generate a text-to-video or video-to-video, but not image-to-video. 
<img width="1257" alt="Screenshot 2024-11-16 at 14 19 02" src="https://github.com/user-attachments/assets/6cf017ab-7991-4382-b1df-40e2bd27cfcd">
<img width="1402" alt="Screenshot 2024-11-16 at 14 19 21" src="https://github.com/user-attachments/assets/059e6b3e-6e1a-4c89-8cd4-7471cffd4b65">

Traceback (most recent call last):
  File "/home/bixbit/.local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/bixbit/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/bixbit/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/bixbit/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/bixbit/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/bixbit/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/bixbit/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/bixbit/.local/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/home/bixbit/EasyAnimate/easyanimate/ui/ui.py", line 430, in generate
    raise gr.Error(f"Please select an image to video pretrained model while using image to video.")
gradio.exceptions.Error: 'Please select an image to video pretrained model while using image to video.'

**Comment by yunkchen** [comment]
Try to refresh Model checkpoints Dropdown and reload model checkpoint.
