### ISSUE TITLE
UnboundLocalError: local variable 'batch_video_path' referenced before assignment

### ISSUE THREAD

**Issue by LiuWeijunAntihos** [aigc-apps/EasyAnimate#166]
In stage3 of video caption

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/workspace/EasyAnimate/easyanimate/video_caption/caption_rewrite.py", line 250, in <module>
[rank0]:     main()
[rank0]:   File "/root/workspace/EasyAnimate/easyanimate/video_caption/caption_rewrite.py", line 209, in main
[rank0]:     for (video_path, prompt, output) in zip(batch_video_path, batch_prompt, batch_output):
[rank0]: UnboundLocalError: local variable 'batch_video_path' referenced before assignment

**Comment by LiuWeijunAntihos** [comment]
thx
