### ISSUE TITLE
v5 7b 报错，t2v 和 i2v 都报错

### ISSUE THREAD

**Issue by sunjian2015** [aigc-apps/EasyAnimate#167]
```
Traceback (most recent call last):
  File "/mnt/personal/code/EasyAnimate/predict_i2v.py", line 314, in <module>
    sample = pipeline(
             ^^^^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/personal/code/EasyAnimate/easyanimate/pipeline/pipeline_easyanimate_multi_text_encoder_inpaint.py", line 1250, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/personal/code/EasyAnimate/easyanimate/models/transformer3d.py", line 1469, in forward
    hidden_states, encoder_hidden_states = block(
                                           ^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/personal/code/EasyAnimate/easyanimate/models/attention.py", line 1119, in forward
    attn_hidden_states, attn_encoder_hidden_states = self.attn1(
                                                     ^^^^^^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers/models/attention_processor.py", line 502, in EasyAnimate.diffusers.models.attention_processor.Attention.forward
  File "/mnt/personal/code/EasyAnimate/easyanimate/models/processor.py", line 283, in __call__
    query[:, :, text_seq_length:] = apply_rotary_emb(query[:, :, text_seq_length:], image_rotary_emb)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers/models/embeddings.py", line 629, in EasyAnimate.diffusers.models.embeddings.apply_rotary_emb
RuntimeError: The size of tensor a (48) must match the size of tensor b (13104) at non-singleton dimension 1

```

**Comment by bubbliiiing** [comment]
能否提供具体都修改了什么参数呢？

**Comment by sunjian2015** [comment]
> 能否提供具体都修改了什么参数呢？

没有修改参数，就是把代码里的 12B 改称了 7B
![image](https://github.com/user-attachments/assets/f5355690-4de0-4d47-babd-0a2ab5db716a)

我好像找到了原因，把 apply_rotary_emb 这个函数直接写到 processor.py 里能跑，import 好像没有成功。
辛苦大佬看下~
