### ISSUE TITLE
使用EasyAnimateV5 训练出来的lora效果很差，跟没有一样

### ISSUE THREAD

**Issue by yangy996** [aigc-apps/EasyAnimate#168]
100多个短视频，跑了一晚上，就从视频里截了一张图，结构出来的效果非常不理想，和没加载lora的效果差不多，这是什么原因呢？请看视频。

https://github.com/user-attachments/assets/85102f96-304c-4497-8f42-e721be549829

**Comment by yunkchen** [comment]
100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？

**Comment by yangy996** [comment]
> 100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？

基本都是这样的，没加载lora，出来的视频跟这个差不多，只是脸崩的比较厉害

**Comment by yunkchen** [comment]
> > 100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？
> 
> 基本都是这样的，没加载lora，出来的视频跟这个差不多，只是脸崩的比较厉害

如果只为了生成训练数据的场景，可以按照数据处理流程处理下数据，然后在这部分视频片段上finetune模型（非lora）

**Comment by yangy996** [comment]
> > > 100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？
> > 
> > 
> > 基本都是这样的，没加载lora，出来的视频跟这个差不多，只是脸崩的比较厉害
> 
> 如果只为了生成训练数据的场景，可以按照数据处理流程处理下数据，然后在这部分视频片段上finetune模型（非lora）

好的，我试试

**Comment by yangy996** [comment]
> > > 100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？
> > 
> > 
> > 基本都是这样的，没加载lora，出来的视频跟这个差不多，只是脸崩的比较厉害
> 
> 如果只为了生成训练数据的场景，可以按照数据处理流程处理下数据，然后在这部分视频片段上finetune模型（非lora）

大佬，训练出来的transformer模型是分开的，这种的如何加载？
![image](https://github.com/user-attachments/assets/4298a744-5e9c-4a34-8c89-8f6b2e00d8eb)
![image](https://github.com/user-attachments/assets/5eadcc3d-7f82-4c6b-bb61-24c1b983f306)

**Comment by yunkchen** [comment]
> > > > 100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？
> > > 
> > > 
> > > 基本都是这样的，没加载lora，出来的视频跟这个差不多，只是脸崩的比较厉害
> > 
> > 
> > 如果只为了生成训练数据的场景，可以按照数据处理流程处理下数据，然后在这部分视频片段上finetune模型（非lora）
> 
> 大佬，训练出来的transformer模型是分开的，这种的如何加载？ ![image](https://private-user-images.githubusercontent.com/15188456/396340661-4298a744-5e9c-4a34-8c89-8f6b2e00d8eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDcxMjMsIm5iZiI6MTczNDQwNjgyMywicGF0aCI6Ii8xNTE4ODQ1Ni8zOTYzNDA2NjEtNDI5OGE3NDQtNWU5Yy00YTM0LThjODktOGY2YjJlMDBkOGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYjY5NmFjNDYwZmRmYzg2MjdiMmM5YjE5MTUyNmE0NzA2Y2VmYmMwY2MxMjQ4ZmMyNzE2MDUzNWU4Y2ZlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XUwqB1w73qNrJqfYmaou61NY1TVMtAmc_k3m5QrGCXU) ![image](https://private-user-images.githubusercontent.com/15188456/396340776-5eadcc3d-7f82-4c6b-bb61-24c1b983f306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDcxMjMsIm5iZiI6MTczNDQwNjgyMywicGF0aCI6Ii8xNTE4ODQ1Ni8zOTYzNDA3NzYtNWVhZGNjM2QtN2Y4Mi00YzZiLWJiNjEtMjRjMWI5ODNmMzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMzIyOGI2YTFhMzA5ZTMwZmMzZTYzOTJmYjVjYWJiNTZhNzdmNWQ0ZDgwODQzMjJjMjgzM2Q4NDU3MDAwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lNYmRQNfYQT93-p0T3gB39SYYmcxuGSUhodkCoj_10w)

这个相当于原来的transformer目录，放在一个目录下即可，其它vae之类的用原来的；
例如models下面创建个新的模型目录，v5的放进来，但是transformer部分用你训练的

**Comment by yangy996** [comment]
> > > > > 100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？
> > > > 
> > > > 
> > > > 基本都是这样的，没加载lora，出来的视频跟这个差不多，只是脸崩的比较厉害
> > > 
> > > 
> > > 如果只为了生成训练数据的场景，可以按照数据处理流程处理下数据，然后在这部分视频片段上finetune模型（非lora）
> > 
> > 
> > 大佬，训练出来的transformer模型是分开的，这种的如何加载？ ![image](https://private-user-images.githubusercontent.com/15188456/396340661-4298a744-5e9c-4a34-8c89-8f6b2e00d8eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDcxMjMsIm5iZiI6MTczNDQwNjgyMywicGF0aCI6Ii8xNTE4ODQ1Ni8zOTYzNDA2NjEtNDI5OGE3NDQtNWU5Yy00YTM0LThjODktOGY2YjJlMDBkOGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYjY5NmFjNDYwZmRmYzg2MjdiMmM5YjE5MTUyNmE0NzA2Y2VmYmMwY2MxMjQ4ZmMyNzE2MDUzNWU4Y2ZlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XUwqB1w73qNrJqfYmaou61NY1TVMtAmc_k3m5QrGCXU) ![image](https://private-user-images.githubusercontent.com/15188456/396340776-5eadcc3d-7f82-4c6b-bb61-24c1b983f306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDcxMjMsIm5iZiI6MTczNDQwNjgyMywicGF0aCI6Ii8xNTE4ODQ1Ni8zOTYzNDA3NzYtNWVhZGNjM2QtN2Y4Mi00YzZiLWJiNjEtMjRjMWI5ODNmMzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMzIyOGI2YTFhMzA5ZTMwZmMzZTYzOTJmYjVjYWJiNTZhNzdmNWQ0ZDgwODQzMjJjMjgzM2Q4NDU3MDAwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lNYmRQNfYQT93-p0T3gB39SYYmcxuGSUhodkCoj_10w)
> 
> 这个相当于原来的transformer目录，放在一个目录下即可，其它vae之类的用原来的； 例如models下面创建个新的模型目录，v5的放进来，但是transformer部分用你训练的

大佬，请问下，我用单卡A800 80G的显存，训练这100多个视频，为什么还会随机出现显存溢出的情况？

**Comment by yunkchen** [comment]
> > > > > > 100多个短视频是怎样的？没加载lora跑出来结果又是怎样的？
> > > > > 
> > > > > 
> > > > > 基本都是这样的，没加载lora，出来的视频跟这个差不多，只是脸崩的比较厉害
> > > > 
> > > > 
> > > > 如果只为了生成训练数据的场景，可以按照数据处理流程处理下数据，然后在这部分视频片段上finetune模型（非lora）
> > > 
> > > 
> > > 大佬，训练出来的transformer模型是分开的，这种的如何加载？ ![image](https://private-user-images.githubusercontent.com/15188456/396340661-4298a744-5e9c-4a34-8c89-8f6b2e00d8eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDcxMjMsIm5iZiI6MTczNDQwNjgyMywicGF0aCI6Ii8xNTE4ODQ1Ni8zOTYzNDA2NjEtNDI5OGE3NDQtNWU5Yy00YTM0LThjODktOGY2YjJlMDBkOGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYjY5NmFjNDYwZmRmYzg2MjdiMmM5YjE5MTUyNmE0NzA2Y2VmYmMwY2MxMjQ4ZmMyNzE2MDUzNWU4Y2ZlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XUwqB1w73qNrJqfYmaou61NY1TVMtAmc_k3m5QrGCXU) ![image](https://private-user-images.githubusercontent.com/15188456/396340776-5eadcc3d-7f82-4c6b-bb61-24c1b983f306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDcxMjMsIm5iZiI6MTczNDQwNjgyMywicGF0aCI6Ii8xNTE4ODQ1Ni8zOTYzNDA3NzYtNWVhZGNjM2QtN2Y4Mi00YzZiLWJiNjEtMjRjMWI5ODNmMzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMzIyOGI2YTFhMzA5ZTMwZmMzZTYzOTJmYjVjYWJiNTZhNzdmNWQ0ZDgwODQzMjJjMjgzM2Q4NDU3MDAwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lNYmRQNfYQT93-p0T3gB39SYYmcxuGSUhodkCoj_10w)
> > 
> > 
> > 这个相当于原来的transformer目录，放在一个目录下即可，其它vae之类的用原来的； 例如models下面创建个新的模型目录，v5的放进来，但是transformer部分用你训练的
> 
> 大佬，请问下，我用单卡A800 80G的显存，训练这100多个视频，为什么还会随机出现显存溢出的情况？

随机还是必现？有报错的日志么？

**Comment by yunkchen** [comment]
这一开始就报错了，是不是CUDA_VISIBLE_DEVICE没有配置对，日志里还有cuda:1，cuda:2的，不是单卡

**Comment by yangy996** [comment]
> 这一开始就报错了，是不是CUDA_VISIBLE_DEVICE没有配置对，日志里还有cuda:1，cuda:2的，不是单卡

不是，这个我直接复现哪个显存溢出的问题，我重新跑下，打印下单卡的

**Comment by yangy996** [comment]
> > 这一开始就报错了，是不是CUDA_VISIBLE_DEVICE没有配置对，日志里还有cuda:1，cuda:2的，不是单卡
> 
> 不是，这个我直接复现哪个显存溢出的问题，我重新跑下，打印下单卡的

好像设置 CUDA_VISIBLE_DEVICE=0 不生效，强制多卡训练了
![image](https://github.com/user-attachments/assets/c5946b9e-b494-4a38-a632-a9313cc61ca3)

**Comment by yangy996** [comment]
> > > 这一开始就报错了，是不是CUDA_VISIBLE_DEVICE没有配置对，日志里还有cuda:1，cuda:2的，不是单卡
> > 
> > 
> > 不是，这个我直接复现哪个显存溢出的问题，我重新跑下，打印下单卡的
> 
> 好像设置 CUDA_VISIBLE_DEVICE=0 不生效，强制多卡训练了 ![image](https://private-user-images.githubusercontent.com/15188456/397332948-c5946b9e-b494-4a38-a632-a9313cc61ca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NTYxMjcsIm5iZiI6MTczNDY1NTgyNywicGF0aCI6Ii8xNTE4ODQ1Ni8zOTczMzI5NDgtYzU5NDZiOWUtYjQ5NC00YTM4LWE2MzItYTkzMTNjYzYxY2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAwNTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNzdkMDIwYjcyZjgwNTBiNTRiYmFhMzE2MmNkZTljZDdlNzFjZDE2OWVlMjAxMTM4ZTU5ZmIwZjBjMjllYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kMHqgjr57iMeGdAVjd9oVyeaLB0COwdit1zlhE56JhM)

改了下代码，单卡训练，显存溢出还是出现了，错误如下：


12/19/2024 21:38:05 - INFO - __main__ - Saved state to output_dir/checkpoint-1100
Steps:   1%|▏         | 1116/75500 [3:25:53<302:03:11, 14.62s/it, lr=2e-5, step_loss=0.014] embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21                                                , 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(42, 24) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(42, 24) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(21, 12) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(52, 30) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(52, 30) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(52, 30) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(42, 24) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(42, 24) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(42, 24) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(42, 24) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((0, 14), (30, 31)) grid_size=(42, 24) in_cache=1 cache_size=47
embed_dim=64 crops_coords=((2, 0), (28, 45)) grid_size=(48, 84) in_cache=1 cache_size=47
Traceback (most recent call last):
  File "/projects/ocr_sd/EasyAnimate/scripts/train.py", line 2100, in <module>
    main()
  File "/projects/ocr_sd/EasyAnimate/scripts/train.py", line 1712, in main
    latents = _batch_encode_vae(pixel_values)
  File "/projects/ocr_sd/EasyAnimate/scripts/train.py", line 1689, in _batch_encode_vae
    pixel_values_bs = vae.encode(pixel_values_bs)[0]
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/easyanimate/models/autoencoder_magvit.py", line 316, in encode
    h = self.encoder(x)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/easyanimate/vae/ldm/models/omnigen_enc_dec.py", line 285, in forward
    next_frames = self.single_forward(x[:, :, i: i + self.mini_batch_encoder, :, :], None, None)
  File "/projects/ocr_sd/EasyAnimate/easyanimate/vae/ldm/models/omnigen_enc_dec.py", line 247, in single_forward
    x = torch.utils.checkpoint.checkpoint(
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/_compile.py", line 31, in inner
    return disable_fn(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
    return fn(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 488, in checkpoint
    ret = function(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/easyanimate/vae/ldm/models/omnigen_enc_dec.py", line 20, in custom_forward
    return module(*inputs)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/easyanimate/vae/ldm/modules/vaemodules/down_blocks.py", line 203, in forward
    x = conv(x)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/easyanimate/vae/ldm/modules/vaemodules/common.py", line 310, in forward
    x = self.conv1(x)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/projects/ocr_sd/EasyAnimate/easyanimate/vae/ldm/modules/vaemodules/common.py", line 141, in forward
    return torch.concat(outputs, 2)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1008.00 MiB. GPU 0 has a total capacity of 79.15 GiB of which 769.81 MiB is free. Includi                                                ng non-PyTorch memory, this process has 78.37 GiB memory in use. Of the allocated memory 65.60 GiB is allocated by PyTorch, and 12.26 GiB is reserved b                                                y PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentat                                                ion.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Steps:   1%|▏         | 1116/75500 [3:25:55<228:44:49, 11.07s/it, lr=2e-5, step_loss=0.014]
Traceback (most recent call last):
  File "/projects/ocr_sd/EasyAnimate/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/projects/ocr_sd/EasyAnimate/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/projects/ocr_sd/EasyAnimate/venv/bin/python3', 'scripts/train.py', '--pretrained_model_name_or_                                                path=models/EasyAnimateV5-7b-zh-InP', '--train_data_dir=/backup/wanjun/dataset/videos_clips/data/', '--train_data_meta=/backup/wanjun/dataset/videos_cl                                                ips/save/train_panda_70m.json', '--config_path', 'config/easyanimate_video_v5_magvit_multi_text_encoder.yaml', '--image_sample_size=1024', '--video_sam                                                ple_size=256', '--token_sample_size=512', '--video_sample_stride=3', '--video_sample_n_frames=49', '--train_batch_size=1', '--video_repeat=1', '--gradi                                                ent_accumulation_steps=1', '--dataloader_num_workers=8', '--num_train_epochs=100', '--checkpointing_steps=100', '--learning_rate=2e-05', '--lr_schedule                                                r=constant_with_warmup', '--lr_warmup_steps=100', '--seed=42', '--output_dir=output_dir', '--gradient_checkpointing', '--mixed_precision=bf16', '--adam                                                _weight_decay=5e-3', '--adam_epsilon=1e-10', '--vae_mini_batch=1', '--max_grad_norm=0.05', '--random_hw_adapt', '--training_with_video_token_length', '                                                --not_sigma_loss', '--enable_bucket', '--uniform_sampling', '--train_mode=inpaint', '--trainable_modules', '.', '--enable_xformers_memory_efficient_att                                                ention', '--low_vram']' returned non-zero exit status 1.
