### ISSUE TITLE
Version of Pytorch Lightning

### ISSUE THREAD

**Issue by alfredplpl** [aigc-apps/EasyAnimate#38]
Nice work!

By the way, what version pytorch lightning you use in this repository?
1.6.1?

I got the this error:

```bash
  | Name            | Type                   | Params
-----------------------------------------------------------
0 | encoder         | Encoder                | 100 M 
1 | decoder         | Decoder                | 145 M 
2 | quant_conv      | Conv3d                 | 72    
3 | post_quant_conv | Conv3d                 | 20    
4 | loss            | LPIPSWithDiscriminator | 21.1 M
-----------------------------------------------------------
252 M     Trainable params
14.7 M    Non-trainable params
267 M     Total params
1,068.244 Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]Summoning checkpoint.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/my_raid/github/EasyAnimate/scripts/train_vae.py", line 740, in <module>
[rank0]:     trainer.fit(model, data)
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
[rank0]:     self._call_and_handle_interrupt(
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
[rank0]:     return trainer_fn(*args, **kwargs)
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
[rank0]:     results = self._run(model, ckpt_path=self.ckpt_path)
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
[rank0]:     return self._run_train()
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
[rank0]:     self._run_sanity_check()
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1404, in _run_sanity_check
[rank0]:     val_loop._reload_evaluation_dataloaders()
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 239, in _reload_evaluation_dataloaders
[rank0]:     self.trainer.reset_val_dataloader()
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1948, in reset_val_dataloader
[rank0]:     self.num_val_batches, self.val_dataloaders = self._data_connector._reset_eval_dataloader(
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 389, in _reset_eval_dataloader
[rank0]:     dataloaders = [self._prepare_dataloader(dl, mode=mode) for dl in dataloaders if dl is not None]
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 389, in <listcomp>
[rank0]:     dataloaders = [self._prepare_dataloader(dl, mode=mode) for dl in dataloaders if dl is not None]
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 300, in _prepare_dataloader
[rank0]:     dataloader = _update_dataloader(dataloader, sampler, mode=mode)
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py", line 176, in _update_dataloader
[rank0]:     dl_kwargs = _get_dataloader_init_kwargs(dataloader, sampler, mode=mode)
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py", line 230, in _get_dataloader_init_kwargs
[rank0]:     dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode=mode))
[rank0]:   File "/home/ozakiy/anaconda3/envs/easyanimate/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py", line 286, in _dataloader_init_kwargs_resolve_sampler
[rank0]:     batch_sampler = type(batch_sampler)(
[rank0]: TypeError: ImageVideoSampler.__init__() missing 1 required positional argument: 'dataset'

```

Is this related in pytorch lightning?

**Comment by yunkchen** [comment]
Torch>=2.2.0 is sugguested.

**Comment by alfredplpl** [comment]
Thank you for your reply.
 I use torch==2.3.0.
But, this problem occurs.

**Comment by alfredplpl** [comment]
I use this repository for training, not inference.
